### ISSUE TITLE
Fix "filter by dietary restriction" option

### ISSUE THREAD

**Issue by HirdayGupta** [ucladevx/Bruin-Bite-iOS#10]
The feature is neither fully functional nor correctly implemented in its current state. 

Get the feature working so that if a dietary restriction is selected, then the overview menus we display only contain those items that conform to the restriction. Maybe even pull the user's default dietary restriction from his profile (but always leave the option open for the user to view the full menu)

**Comment by ayush-patel** [comment]
We eliminated the bottom allergen bar - please refer to the latest design on figma. However we still have the ability to modify the dietary restriction, so we still need to build the feature to be able to filter the menus just not from the old design of the bar at the bottom.

**Comment by HirdayGupta** [comment]
@ayush-patel say a user signs up with a `gluten-free` dietary restriction, then will he only be able to see the gluten-free menus when he's using the app?

**Comment by ayush-patel** [comment]
yes we'll hide the other menu items. this preference can always be changed from settings later

**Comment by HirdayGupta** [comment]
@ayush-patel are we sure that is the best way to go? It might be a little unintuitive to not have those controls while viewing the menus (or to have an option that is hidden behind a couple of screens affect a feature that we expect to be used very heavily?)

**Comment by ayush-patel** [comment]
Yes I agree. That is what I initially had, but Fiona and Nidhi liked it this way. I’ll talk to them about this. Thanks for bringing it up!

**Comment by ayush-patel** [comment]
@HirdayGupta we are keeping the allergen-bar from the original implementation to make it easier to navigate!
