### ISSUE TITLE
Either remove previous dates/times or store date from previous day and display

### ISSUE THREAD

**Issue by ftang1996** [ucladevx/Bruin-Bite-iOS#29]

**Comment by HirdayGupta** [comment]
@ayush-patel I guess it would be better to remove the previous day option altogether from our menu?

**Comment by ayush-patel** [comment]
@TerreneHo should have it before milestone 2

**Comment by HirdayGupta** [comment]
You mean @TerrenceHo will be sending us data for Previous Day?

**Comment by ayush-patel** [comment]
Yes that’s correct
